columns:
  gender:
    type: categorical
    allowed: ['Female', 'Male']
  SeniorCitizen:
    type: integer
    min: 0
    max: 1
  Partner:
    type: categorical
    allowed: ['Yes', 'No']
  Dependents:
    type: categorical
    allowed: ['Yes', 'No']
  tenure:
    type: integer
    min: 0
  PhoneService:
    type: categorical
    allowed: ['Yes', 'No']
  MultipleLines:
    type: categorical
    allowed: ['Yes', 'No', 'No phone service']
  InternetService:
    type: categorical
    allowed: ['DSL', 'Fiber optic', 'No']
  OnlineSecurity:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  OnlineBackup:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  DeviceProtection:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  TechSupport:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  StreamingTV:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  StreamingMovies:
    type: categorical
    allowed: ['Yes', 'No', 'No internet service']
  Contract:
    type: categorical
    allowed: ['Month-to-month', 'One year', 'Two year']
  PaperlessBilling:
    type: categorical
    allowed: ['Yes', 'No']
  PaymentMethod:
    type: categorical
    allowed:
      - 'Electronic check'
      - 'Mailed check'
      - 'Bank transfer (automatic)'
      - 'Credit card (automatic)'
  MonthlyCharges:
    type: float
    min: 0
  TotalCharges:
    type: float
    min: 0
  numAdminTickets:
    type: integer
    min: 0
  numTechTickets:
    type: integer
    min: 0
  Churn:
    type: integer
    allowed: [0, 1]
